name: BUILD

on:
#  release:
#    type: [published]
  pull_request:
  push:
    tags:
      - '*'
    
jobs:
  variables:
    runs-on: ubuntu-22.04-arm
    outputs:
      ARCH_LIST: ${{ env.ARCH_LIST }}
      ADDON_LIST: ${{ env.ADDON_LIST }}
      DOCKER_ARGS: ${{ env.DOCKER_ARGS }}
    env:
      CPCD_VERSION: v4.7.0
      GECKO_SDK_VERSION: v2025.6.0
      UNIVERSAL_SILABS_FLASHER: 0.0.22
    steps:
      - uses: actions/checkout@v3

      - name: "ARGS: default"
        run: |
          echo "ADDON_LIST=['silabs-multiprotocol-ember']" >> $GITHUB_ENV
          echo "DOCKER_ARGS=--no-latest --test" >> $GITHUB_ENV
      - name: "ARGS: silabs-multiprotocol-ember" # Build of addon release version
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        run: |
          echo "ADDON_LIST=['silabs-multiprotocol-ember']" >> $GITHUB_ENV
          echo "DOCKER_ARGS=--no-cache" >> $GITHUB_ENV
#          echo "DOCKER_ARGS=--build-args CPCD_VERSION=${{ env.CPCD_VERSION }}" >> $GITHUB_ENV
#          echo "DOCKER_ARGS=--build-args GECKO_SDK_VERSION=${{ env.GECKO_SDK_VERSION }}" >> $GITHUB_ENV
#          echo "DOCKER_ARGS=--build-args UNIVERSAL_SILABS_FLASHER=${{ env.UNIVERSAL_SILABS_FLASHER }}" >> $GITHUB_ENV


  build:
    runs-on: buildjet-8vcpu-ubuntu-2204
    permissions:
      contents: read
      packages: write
    needs: variables
    env:
      DOCKER_ARGS: ${{needs.variables.outputs.DOCKER_ARGS}}
    strategy:
      matrix:
        arch:
          - arch: aarch64
            from: ghcr.io/home-assistant/aarch64-base-debian:bookworm
          - arch: armv7
            from: ghcr.io/home-assistant/armv7-base-debian:bookworm
          - arch: amd64
            from: ghcr.io/home-assistant/amd64-base-debian:bookworm
    steps:
      - uses: actions/checkout@v3
      - name: set version
        if: (startsWith(github.ref, 'refs/tags/'))
        run: |
          jq '.version = "${{ github.ref_name }}"' silabs-multiprotocol-ember/config.json > silabs-multiprotocol-ember/config.json.tmp
          mv silabs-multiprotocol-ember/config.json.tmp silabs-multiprotocol-ember/config.json
          cat silabs-multiprotocol-ember/config.json
          echo vars: ${{ vars.DOCKER_LOGIN }}
          echo env: ${{ env.DOCKER_LOGIN }}
      - uses: docker/login-action@v2
#        if: (startsWith(github.ref, 'refs/tags/'))
        with:
          registry: ghcr.io
          username: ${{ vars.DOCKER_LOGIN }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
#        if: (startsWith(github.ref, 'refs/tags/'))
        with:
          username: ${{ vars.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64,linux/amd64,linux/armv7
          image: tonistiigi/binfmt:latest
      - name: Build
        run: |
          docker run --rm --privileged \
              -v /home/runner/.docker:/root/.docker \
              --ulimit memlock=100000000000:100000000000 \
              -v /run/docker.sock:/run/docker.sock:rw \
              -v $(pwd)/silabs-multiprotocol-ember:/data homeassistant/amd64-builder --${{ matrix.arch.arch }} -t /data \
              ${{ env.DOCKER_ARGS }}
#          docker push ghcr.io/se7ven/${{ matrix.arch.arch }}-addon-silabs-multiprotocol-ebmer:$GITHUB_REF


